### ISSUE TITLE
Container GPU test example?

### ISSUE THREAD

**Issue by davodogster** [waikato-datamining/mmsegmentation#1]
Hi guys thanks for the awesome work!

Is there an example script when can run to test it trains properly and uses our local machines GPU (im CUDA 11.6, 3090).
e.g mmseg_train test_gpu_train_model.py

Cheers! Sam

**Comment by fracpete** [comment]
No, unfortunately not.

However, I'm in the (slow) process of compiling tutorials for our various docker images and I've added one for MMSegmentation:
https://www.data-mining.co.nz/applied-deeplearning/image_segmentation/mmsegmentation/

I've used our own 3090 to run while compiling the instructions, so it should work (the container already contains CUDA 11.1, i.e., 3xxx series compatible).

While writing these instructions, I came across a couple of minor bugs regarding outputting config files with `mmseg_config`. Hence I pushed out a new version of the docker images.

**Comment by davodogster** [comment]
@fracpete Thank you for this! It looks very helpful.

**Comment by davodogster** [comment]
Hi @fracpete 

Is this error bad?
![image](https://user-images.githubusercontent.com/46079516/196084342-5e7a3a4c-f81a-4c75-98fa-3734ed065130.png)

And which container is correct to use?

![image](https://user-images.githubusercontent.com/46079516/196084668-2d7f161b-32db-4410-ba9e-372ebc04a7b2.png)
 or
![image](https://user-images.githubusercontent.com/46079516/196084748-12bcc7fd-50d4-42d3-8143-e69f3f9a24fa.png)

Thank you, Sam

**Comment by fracpete** [comment]
Both images are the same. I deploy them on docker hub as well for people not in NZ for faster downloads.

What error are you referring to: libcudart or matplotlib config dir?

Also, what's the context of this output?

**Comment by davodogster** [comment]
The context is that I'm trying to run through the example here:

https://www.data-mining.co.nz/applied-deep-learning/image_segmentation/mmsegmentation/

I was able to progress past the errors and did the file conversion and modified the pspnet_r50.py file.
Then I was receiving shm/dataloader worker memory errors but I figured out we need to add  --shm-size=Xg when running the docker command to launch the training, and that solved the issue now the model is training :)

Thanks, Sam
![image](https://user-images.githubusercontent.com/46079516/196296676-ecaea1d4-c0b3-4575-9869-f588ac44039b.png)

**Comment by fracpete** [comment]
Thanks, for the feedback. I've added `--shm-size 8G` to the commands to avoid future problems.

**Comment by davodogster** [comment]
Thanks! Is there a way to interrupt the training? Ctrl+C or Ctrl X does nothing and it continues training.

**Comment by fracpete** [comment]
Unfortunately, Ctrl+C doesn't work. You have to determine the process ID (PID) of a Python process with a high load using `top` and then stop that process via `kill PID`.

**Comment by davodogster** [comment]
Thank you that works
