### ISSUE TITLE
Is convert MMSeg Pytorch model to ONNX possible with your container?

### ISSUE THREAD

**Issue by davodogster** [waikato-datamining/mmsegmentation#2]
Hi I'm trying to follow:
https://mmsegmentation.readthedocs.io/en/latest/useful_tools.html

![image](https://user-images.githubusercontent.com/46079516/197067634-383909d4-0947-4fa7-b069-aec34a7ffc54.png)

![image](https://user-images.githubusercontent.com/46079516/197068333-decf110c-876e-4ad9-aaef-7ae5c0fe0ae9.png)

![image](https://user-images.githubusercontent.com/46079516/197068386-d3ca5722-e586-4131-93ed-4db1cf45442a.png)

Is convert MMSeg Pytorch model to ONNX possible with your container? Would it be easy to add into the docker build? I'm not sure how to do it. Cheers, Sam

I am also interested in ONNX to TensorRT.
EDIT: I just discovered this which looks useful https://github.com/open-mmlab/mmdeploy

**Comment by fracpete** [comment]
I usually use the models natively rather than exporting them, so not really high on my priority list. Please feel free to do a PR.

In terms of permissions denied for `/.local`, map that directory to your host.

**Comment by fracpete** [comment]
The just published docker images for version 0.30.0 (CPU and CUDA 11.1) have ONNX support built-in and script `mmseg_onnx` for convenience.
