### ISSUE TITLE
How to evaluate trained model on test set using waikatommseg?

### ISSUE THREAD

**Issue by davodogster** [waikato-datamining/mmsegmentation#3]
Hi is it possible to load the model and evaluate metrics on the test images using mmseg_predict_poll or your docker container?

When training it only outputs val metrics. Cheers!

**Comment by fracpete** [comment]
Have you tried the following tool that comes with mmsegmentation?

https://mmsegmentation.readthedocs.io/en/latest/inference.html?highlight=evaluate#test-a-dataset

**Comment by davodogster** [comment]
Thanks! I'm trying that now (inside your docker container). Do you know why it would give a permission denied error? Do you think it could be docker related? 
![image](https://user-images.githubusercontent.com/46079516/199607208-63c05b6a-7434-44ec-9f87-4ec8ed8ac6ba.png)

**Comment by fracpete** [comment]
Some of the **mm*** tools have a hard-coded path `/work_dirs` that they use internally(I've run into that every now and then).
Try mapping `/work_dirs` to a work directory on your host using a `-v` mapping in your docker command.

**Comment by davodogster** [comment]
Thanks Peter! It worked for me.

![image](https://user-images.githubusercontent.com/46079516/199610744-20679594-e034-443f-bc75-7d63c7292e20.png)
`python /mmsegmentation/tools/test.py /workspace/output/FM_binary-mmseg-pspnet50/fcn_unet.py /workspace/output/FM_binary-mmseg-pspnet50/iter_160000.pth --eval mIoU
`

**Comment by fracpete** [comment]
Cool!
