### ISSUE TITLE
Is there a container for MMSeg v1.0?

### ISSUE THREAD

**Issue by davodogster** [waikato-datamining/mmsegmentation#4]
- (Unifies interfaces of all components based on [MMEngine](https://github.com/open-mmlab/mmengine).
- Faster training and testing speed with complete support of mixed precision training.
- Refactored and more flexible [architecture](https://mmsegmentation.readthedocs.io/en/1.x/overview.html).)

Cheers, Sam

**Comment by fracpete** [comment]
Not at this stage. However, I have a project starting in the new year where I might use segmentation. New images take some time tp develoo, as they require a fair bit of testing. Code often changes in subtle ways...

**Comment by davodogster** [comment]
Ok thanks for the info! Also, I was trying to output bluchannel prediction masks but this still saved them as grayscale. Am I doing it correctly?
  --config /workspace/segformer_scratch/segformer_1024x1024.py \
  --prediction_format bluechannel \
  --prediction_in /workspace/predictions/in \
  --prediction_out /workspace/predictions/out

**Comment by fracpete** [comment]
What does `file ONEOFYOURPNGFILES.png` output?
Bluechannel files are 24bit PNG files with indices in the blue channel only. Instead of 8bit single channel gray scale ones.

**Comment by fracpete** [comment]
There are currently only release candidates (RC) out for 1.0.0 (rc3 at time of writing).
It's usually advised to wait a few releases after a major refactoring to get all the kinks ironed out.

**Comment by fracpete** [comment]
I've made docker images for 1.1.0 available (02528d3929edbe6abe04e7d170ecb5129bc3f23f).
